apiVersion: apps/v1
kind: Deployment
metadata:
  name: dayoapp
spec:
  selector:
    matchLabels:
      app: dayoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: dayoapp
    spec:
      containers:
      - name: dayoapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
